### ISSUE TITLE
Potential incompatibility with HOOBS when registering Platform

### ISSUE THREAD

**Issue by andrewtzn** [JarekToro/homebridge-roku-tv#3] opened 2020-05-22 19:49 UTC
Hi JarekToro,

Thank you for creating this plugin.

Sorry I'm a noob here.

But how do you set this up?

I entered pollingInterval in the config file.

What else should I put there?

On the log, I am getting "Your config.json is requesting the platform "RokuTV" which has not been published by any installed plugins."

I am running a HOOBS server.

Thank you for your help!

**Comment by JarekToro** [comment] 2020-05-25 18:45
Make sure you have the latest version. my config is this
```json
"platforms": [

        {
            "pollingInterval": 30000,
            "platform": "RokuTV"
        },
]
```

**Comment by andrewtzn** [comment] 2020-05-25 19:29
Thank you for updating the plugin.
I just tried using your config, but I am still getting the same error from the log. 😕

`The requested platform "RokuTV" was not registered by any plugin.`
`Your config.json is requesting the platform "RokuTV" which has not been published by any installed plugins.`

Please let me know what additional information you will need in order to troubleshoot this issue.

**Comment by andrewtzn** [comment] 2020-05-25 19:36
I also tried using this config but didn't help.

```
{
            "pollingInterval": 30000,
            "platform": "RokuTV",
            "plugin_map": {
                "plugin_name": "homebridge-roku-tv-plugin"
            },
            "excludedApps": []
}
```

**Comment by JarekToro** [comment] 2020-05-25 22:00
You should try to unistall remove it from your config and try again

**Comment by andrewtzn** [comment] 2020-05-25 22:19
Thank you for getting back to me JarekToro!

Reinstalled the plugin with config. The issue still persisted. 
Also tried restarting the server and reinstalling the plugin, but that didn't resolve it.😕

Not sure what's preventing it from running.

**Comment by andrewtzn** [comment] 2020-05-25 22:38
I started debug mode and here's the log:

`Loaded plugin "homebridge-roku-tv-plugin".`
`Registering platform "RokuTV"`
`The requested platform "RokuTV" was not registered by any plugin.`
`Your config.json is requesting the platform "RokuTV" which has not been published by any installed plugins.`

It seems like the plugin loaded but failed to register.

**Comment by JarekToro** [comment] 2020-05-25 23:05
I am unsure what the problem may be. I'm unfamiliar with HOOBs but from what I can tell it should be compatible with my plugin.

**Comment by JarekToro** [comment] 2020-05-25 23:08
For what it is worth here is what my logs say (using homebridge) when the plugin loads and registers
```
[5/25/2020, 15:01:56] ---
[5/25/2020, 15:01:56] Loaded plugin: homebridge-roku-tv-plugin@1.0.7
[5/25/2020, 15:01:56] Registering platform 'homebridge-roku-tv-plugin.RokuTV'
[5/25/2020, 15:01:56] ---
```

**Comment by alecgarcia** [comment] 2020-05-26 02:48
I was experiencing the same issue as @andrewtzn. I went ahead and downloaded your platform and ran it in my home bridge test environment and I am still experiencing the same issue. Here is the output I am getting.
`[5/25/2020, 9:46:10 PM] Error loading platform requested in your config.json at position 2
[5/25/2020, 9:46:10 PM] Error: The requested platform 'RokuTV' was not registered by any plugin.
    at PluginManager.getPluginForPlatform (/usr/local/lib/node_modules/homebridge/src/pluginManager.ts:223:15)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:386:37
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:373:27)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:152:29)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:78:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1176:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
    at Module.load (internal/modules/cjs/loader.js:1040:32)
    at Function.Module._load (internal/modules/cjs/loader.js:929:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47`

**Comment by JarekToro** [comment] 2020-05-26 03:25
So is this local test environment just home bridge or is it also a Hoobs environment?

This is successfully running on home-bridge for other users. If your environment is just home bridge is there any thing unique about your setup that you think might be related? I’m really unsure where to start as I’m unable to reproduce the error.

Can you also provide a full log of when it registers accessories and platforms.

**Comment by askovi** [comment] 2020-05-26 03:32
I found the issue in your platform registration. I'll submit a PR shortly.

**Comment by alecgarcia** [comment] 2020-05-26 03:34
I am just running homebridge directly from my Mac. I even removed my other test platform to test. 
```
$ homebridge
[5/25/2020, 10:31:48 PM] Loaded config.json with 0 accessories and 1 platforms.
[5/25/2020, 10:31:48 PM] ---
[5/25/2020, 10:31:48 PM] Loaded plugin: homebridge-roku-platform
[5/25/2020, 10:31:48 PM] Registering platform 'homebridge-roku-platform.RokuPlatform'
[5/25/2020, 10:31:48 PM] ---
[5/25/2020, 10:31:48 PM] ====================
[5/25/2020, 10:31:48 PM] ERROR LOADING PLUGIN homebridge-roku-tv-plugin:
[5/25/2020, 10:31:48 PM] Error: Cannot find module '/usr/local/lib/node_modules/homebridge-roku-tv-master/dist/index.js'
Require stack:
- /usr/local/lib/node_modules/homebridge/lib/plugin.js
- /usr/local/lib/node_modules/homebridge/lib/pluginManager.js
- /usr/local/lib/node_modules/homebridge/lib/api.js
- /usr/local/lib/node_modules/homebridge/lib/index.js
- /usr/local/lib/node_modules/homebridge/lib/cli.js
- /usr/local/lib/node_modules/homebridge/bin/homebridge
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1020:15)
    at Function.Module._load (internal/modules/cjs/loader.js:890:27)
    at Module.require (internal/modules/cjs/loader.js:1080:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Plugin.load (/usr/local/lib/node_modules/homebridge/src/plugin.ts:162:27)
    at /usr/local/lib/node_modules/homebridge/src/pluginManager.ts:119:16
    at Map.forEach (<anonymous>)
    at PluginManager.initializeInstalledPlugins (/usr/local/lib/node_modules/homebridge/src/pluginManager.ts:117:18)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:149:24)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:78:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1176:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
    at Module.load (internal/modules/cjs/loader.js:1040:32)
    at Function.Module._load (internal/modules/cjs/loader.js:929:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
[5/25/2020, 10:31:48 PM] ====================
[5/25/2020, 10:31:48 PM] Loading 1 platforms...
[5/25/2020, 10:31:48 PM] Error loading platform requested in your config.json at position 1
[5/25/2020, 10:31:48 PM] Error: The requested platform 'RokuTV' was not registered by any plugin.
    at PluginManager.getPluginForPlatform (/usr/local/lib/node_modules/homebridge/src/pluginManager.ts:223:15)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:386:37
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:373:27)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:152:29)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:78:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1176:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1196:10)
    at Module.load (internal/modules/cjs/loader.js:1040:32)
    at Function.Module._load (internal/modules/cjs/loader.js:929:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
$ 
```

**Comment by theque9** [comment] 2020-05-26 03:34
> For what it is worth here is what my logs say (using homebridge) when the plugin loads and registers
> 
> ```
> [5/25/2020, 15:01:56] ---
> [5/25/2020, 15:01:56] Loaded plugin: homebridge-roku-tv-plugin@1.0.7
> [5/25/2020, 15:01:56] Registering platform 'homebridge-roku-tv-plugin.RokuTV'
> [5/25/2020, 15:01:56] ---
> ```

What does the 1.0.7 relate to?

**Comment by JarekToro** [comment] 2020-05-26 03:47
Pushing Update should be able to get the latest version.

**Comment by JarekToro** [comment] 2020-05-26 03:52
If it is fixed let me know and I will close this issue

**Comment by andrewtzn** [comment] 2020-05-26 04:19
@JarekToro and @askovi ,

You are awesome! The plugin is running now. I am able to see the activity in the log and I can control the TV in the Home app.

I was actually looking at the index.js file in the dist folder, and found something different when compared to my other plugin's index.js file a few hours ago. (the api.registerPlatform line)
However, I am not expert, so I can't really pinpoint the issue. At least I was on the right track. 😅

Anyway, thank you all for contributing to this awesome plugin!

Stay well everyone!

**Comment by JarekToro** [comment] 2020-05-26 04:24
Stay safe

**Closed** 2020-05-26 04:24 UTC

**Comment by theque9** [comment] 2020-05-26 12:03
@JarekToro This still isn't working for me. I uninstalled all other Roku plugins that could've potentially been an issue and reinstalled this. My config is below and the log is attached. I think the specific issue in the log is:

5/26/2020, 7:56:21 AM - Accessory TCL Roku TV (65R625)experienced an address collision.

[logs-2.txt](https://github.com/JarekToro/homebridge-roku-tv/files/4682021/logs-2.txt)
{
            "platform": "RokuTV",
            "plugin_map": {
                "plugin_name": "homebridge-roku-tv-plugin"
            },
            "pollingInterval": 30000,
            "excludedApps": []
        }

**Comment by JarekToro** [comment] 2020-05-26 12:15
I’m not sure what this is 
```
"plugin_map": {
"plugin_name": "homebridge-roku-tv-plugin"
},
```
But I don’t think it’s needed? Could be wrong I’m really unfamiliar with HOOBS.

I would uninstall and reinstall this.

Also do you have multiple roku TVs?
That is a similar error to the other issue #1

**Comment by theque9** [comment] 2020-06-02 03:26
@JarekToro 
Working now. All I had to do was choose add accessory in the Home app, then select I don’t have a code and both of my Roku devices were able to be added.
